
ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 2000
  ReadTimeout: 5000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0

zuul:
  routes:
    backendRibbon:
      path: /ribbon/**
      stripPrefix: true
      serviceId: backendRibbon
    backendNonRibbon:
      path: /nonribbon/**
      stripPrefix: true
      url: http://localhost:8082/
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 5000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

backendRibbon:
  ribbon:
    listOfServers: localhost:8082
#    MaxAutoRetries: 5
#    ConnectTimeout: 1500
#    ReadTimeout: 1500

logging:
  level:
    com.netflix: DEBUG